### ISSUE TITLE
Time is 12 h off

### ISSUE THREAD

**Issue by lo-co** [NOAA-CSD/las-mfc-ui#10]
@kfroyd says the data file time is 12 h off.  I am unable to reproduce this.  Can someone make sure the system clock is not off by 12 h?

**Comment by kfroyd** [comment]
Data taken today at 14:00 is stamped 02:00 in log file.  12 hours off.
LAS system clock is set correctly to local time, not the problem.

**Comment by lo-co** [comment]
Time is not off by 12 h, it is just improperly formatted.  Used ``hh`` format specifier rather than ``HH``.
