### ISSUE TITLE
q1 being written as dp1

### ISSUE THREAD

**Issue by lo-co** [NOAA-CSD/las-mfc-ui#7]
Per @kfroyd - In last column of data file should contain ``q1`` but seems to contain ``dp1``.

**To be honest, this might be user error and it might not be properly configured. **

**Comment by lo-co** [comment]
@kfroyd - can you check the configuration file and make sure that the configuration coefficients are not 1,0?  Look for something that looks like this

```ini
Sample.a = 5.0
Sample.b = 12.3
```

**Comment by lo-co** [comment]
@kfroyd - did you ever look into this?

**Comment by kfroyd** [comment]
Confirmed that coefficients had been reset to 1,0 at some point.  I set them to 5.0, 12.3.  Not correct coefficients.  Tried using old coefficients, a=48.143, b=0.059476, seemed to make more sense.  
1) What should they be?
2) New problem... data file not being written anywhere.  Ini file points to C:\las-mfc-ui\data.  Folder is empty.
3) Still need to add minimize button to program.

**Comment by lo-co** [comment]
Not sure what the coefficients should be.  The minimize issue was handled in #6.  Was just waiting to hear back from you about the data file...

**Comment by kfroyd** [comment]
Turns out data is being written to C:\data.  It's ignoring the path in 
the ini file.

The time stamp in the data files is 12h off (writing 03:00 for 3pm).

Aga's previous coefficients seem to work.

**Comment by lo-co** [comment]
Coefficients were the issue.  Nothing to be changed.
